modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU Lesser General Public License"

[[mods]]
modId = "aileron"
version = "${version}"
displayName = "Aileron"
authors = "Team Lodestar"
description = '''
A unique and expansive Elytra overhaul
'''
#logoFile = ""

[[dependencies.aileron]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aileron]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"